<?php

namespace Silent\DailyPicsCoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    const cacheTime = 300;

    public function getCategoryForMenu($now)
    {
        $query = $this->_em->createQuery("SELECT c.name, c.slug, count(i.id) as imageCount
                                          FROM SilentDailyPicsCoreBundle:Category c
                                          JOIN c.images i
                                          WHERE i.publishDate <= :now
                                          GROUP BY c.id
                                          ORDER BY c.name ASC");

        $query->setParameter(":now", $now);
        $query->useResultCache(true, self::cacheTime);
        return $query->getArrayResult();
    }


    public function getCategoryBySlug($slug, $now)
    {
        $query = $this->_em->CreateQuery("SELECT c, i
                                 FROM SilentDailyPicsCoreBundle:Category c
                                 JOIN c.images i
                                 WHERE c.slug = :slug
                                 AND i.publishDate <= :now
                                 ORDER BY i.publishDate DESC");

        $query->setParameter(":now", $now);
        $query->setParameter(":slug", $slug);

        $query->useResultCache(true, self::cacheTime);

        return $query->getSingleResult();
    }

}
