imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        site_protocol: "%site_protocol%"
        site_locale: "%locale%"
        site_name: "%site_name%"
        site_name_short: "%site_name_short%"
        site_domain: "%site_domain%"
        ga_id: "%ga_id%"
        site_logo: "%site_logo%"
        site_version: "%site_version%"
        site_facebook_page: "%site_facebook_page%"
        bootstrap_template: "%bootstrap_template%"
        categories_string: "%categories_string%"
        category_string : "%category_string%"
        random_string: "%random_string%"
        base_title: "%base_title%"
        home_title: "%home_title%"
        home_descriptiption: "%home_descriptiption%"
        home_keywords: "%home_keywords%"
        site_launch_year: "%site_launch_year%"
        comment_button_string: "%comment_button_string%"
        authenticate_string: "%authenticate_string%"
        administration_link_string: "%administration_link_string%"
        logout_string: "%logout_string%"
        back_to_site_string: "%back_to_site_string%"
        previous_pics_string: "%previous_pics_string%"
        next_pics_string: "%next_pics_string%"


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


services:
    cache_APC:
        class: Doctrine\Common\Cache\ApcCache

knp_paginator:
    page_range: 10                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: :Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Silent\DailyPicsUserBundle\Entity\User

sonata_admin:
    title: DailyPics Administration

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

stof_doctrine_extensions:
    uploadable:
        default_file_path: %kernel.root_dir%/../web/images
        mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter
        default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo
    orm:
        default:
            sluggable: true
            uploadable: true

liip_imagine:
    resolvers:
        default:
            web_path:
              cache_prefix: "images/cache"
    filter_sets:
        photo_liste:
            filters:
                relative_resize: { widen: 561 }
        photo_seule:
                    filters:
                        relative_resize: { widen: 748 }
        thumb:
            filters:
                thumbnail: { size: [70, 70], mode: inset }