parameters:
#    silent_daily_pics_user.example.class: Silent\DailyPicsUserBundle\Example

services:
#    silent_daily_pics_user.example:
#        class: %silent_daily_pics_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
