silent_daily_pics_core_home:
    path:     /
    defaults: { _controller: SilentDailyPicsCoreBundle:Pics:home }

silent_daily_pics_core_show:
    path:     /photo/{slug}/
    defaults: { _controller: SilentDailyPicsCoreBundle:Pics:showPics }
